module.exports={
    RudderStackUrl:{
        baseUrl:"https://qa.rudderstack.com",
    },
    RudderStackCred:{
        userName:"cataho8779@blaxion.com",
        password:"Assignment1234#"
    }
}