name: Cypress Daily Tests

on:
  schedule:
    - cron: "30 0 * * *"  # Daily at 2:00 AM IST (20:30 UTC)
  workflow_dispatch:       # Manual trigger option

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.14.0

      - name: Install dependencies
        run: npm install
        
      - name: Run Cypress tests (Headless)
        run: npx cypress run --browser chrome --headless
