name: Cypress Daily Tests

on:
  push:                   # Runs on every commit in main branch
    branches:
      - main
  schedule:
    - cron: "30 0 * * *"  # Daily at 6:00 AM IST
  workflow_dispatch:      # Manual trigger option

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.14.0

      - name: Install dependencies
        run: npm install
        
      - name: Run Cypress tests (Headless)
        run: npx cypress run --env envName=app --browser chrome --headless

      - name: Upload Cypress video artifact
        if: always()  # Ensures this runs even if earlier steps failed
        uses: actions/upload-artifact@v4
        with:
          name: cypress-video
          path: cypress/videos/**.mp4
          retention-days: 6
